# Generated by Django 5.2.4 on 2025-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='recurso',
            field=models.FileField(blank=True, null=True, upload_to='recursos_actividades/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('juego', 'Juego Interactivo'), ('sopa_letras', 'Sopa de letras'), ('crucigrama', 'Crucigrama'), ('palabras', 'Juego de palabras'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
