# Generated by Django 5.2.3 on 2025-09-24 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_actividad_tipo_materiacienciasnaturales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('revisada', 'Revisada'), ('calificada', 'Calificada')], default='asignada', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios_profesor', models.TextField(blank=True, help_text='Comentarios del profesor')),
                ('comentarios_estudiante', models.TextField(blank=True, help_text='Comentarios del estudiante')),
                ('archivo_entrega', models.FileField(blank=True, help_text='Archivo de entrega del estudiante', null=True, upload_to='entregas_actividades/')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.actividad')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_por_mi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Actividad',
                'verbose_name_plural': 'Asignaciones de Actividades',
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
