# Generated by Django 5.2.3 on 2025-09-24 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_asignacionactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('matematicas', 'Matemáticas Básicas'), ('lenguaje', 'Lenguaje y Lectura'), ('ciencias', 'Ciencias Naturales'), ('colores_formas', 'Colores y Formas'), ('memoria', 'Juegos de Memoria'), ('logica', 'Lógica Simple'), ('creatividad', 'Creatividad y Arte')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('edad_minima', models.IntegerField(default=3, help_text='Edad mínima recomendada')),
                ('edad_maxima', models.IntegerField(default=12, help_text='Edad máxima recomendada')),
                ('icono', models.CharField(default='🎮', help_text='Emoji o icono para la categoría', max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Juego',
                'verbose_name_plural': 'Categorías de Juegos',
            },
        ),
        migrations.CreateModel(
            name='JuegoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_juego', models.CharField(choices=[('memoria_colores', 'Memoria de Colores'), ('contar_objetos', 'Contar Objetos'), ('formas_geometricas', 'Formas Geométricas'), ('colores_primarios', 'Colores Primarios'), ('animales_sonidos', 'Animales y Sonidos'), ('letras_palabras', 'Letras y Palabras'), ('numeros_basicos', 'Números Básicos'), ('puzzle_simple', 'Puzzle Simple'), ('clasificacion', 'Clasificación de Objetos'), ('secuencias', 'Secuencias Lógicas')], max_length=30)),
                ('nivel_dificultad', models.CharField(choices=[('muy_facil', 'Muy Fácil (3-5 años)'), ('facil', 'Fácil (6-8 años)'), ('intermedio', 'Intermedio (9-12 años)')], default='facil', max_length=15)),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración específica del juego')),
                ('objetivos_aprendizaje', models.TextField(help_text='Qué aprenderán los niños')),
                ('habilidades_desarrolla', models.JSONField(default=list, help_text='Lista de habilidades que desarrolla')),
                ('edad_minima', models.IntegerField(default=3)),
                ('edad_maxima', models.IntegerField(default=12)),
                ('tiempo_estimado', models.IntegerField(default=5, help_text='Tiempo estimado en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('veces_jugado', models.IntegerField(default=0)),
                ('puntuacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='api.categoriajuego')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juego Educativo',
                'verbose_name_plural': 'Juegos Educativos',
                'ordering': ['categoria', 'nivel_dificultad', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PartidaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('abandonada', 'Abandonada')], default='iniciada', max_length=15)),
                ('puntuacion', models.IntegerField(default=0)),
                ('puntuacion_maxima', models.IntegerField(default=100)),
                ('tiempo_jugado', models.IntegerField(default=0, help_text='Tiempo en segundos')),
                ('intentos', models.IntegerField(default=1)),
                ('aciertos', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('datos_partida', models.JSONField(default=dict, help_text='Datos específicos de la partida')),
                ('actividad_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.asignacionactividad')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='api.juegoeducativo')),
            ],
            options={
                'verbose_name': 'Partida de Juego',
                'verbose_name_plural': 'Partidas de Juegos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
