"""
Django settings for edunuñez project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
import urllib.parse
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        env_path = BASE_DIR.parent / '.env'
    load_dotenv(dotenv_path=env_path)
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo: configurar DJANGO_SECRET_KEY en variables de entorno o en .env
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me-in-production'
    else:
        raise ValueError('DJANGO_SECRET_KEY debe estar configurada en producción')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'axes',
    'apps.core',
    'apps.usuarios',
    'apps.cursos',
    'apps.actividades',
    'apps.plantillas',
    'apps.juegos',
    'apps.ciencias',
    'apps.integraciones',
    'auth',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'api.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de CORS para desarrollo y producción según variables de entorno
CORS_ALLOWED_ORIGINS = os.environ.get(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(',')

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

# Permitir headers adicionales
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',
]

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = ['ip_address']
AXES_CACHE = 'default'
AXES_LOCK_OUT_AT_FAILURE = True

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'edunuñez.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(BASE_DIR.parent / 'frontend' / 'build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edunuñez.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL') or os.environ.get('DJANGO_DATABASE_URL')

if DATABASE_URL:
    _url = urllib.parse.urlparse(DATABASE_URL)
    _db_host = _url.hostname or '127.0.0.1'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _url.path.lstrip('/') if _url.path else 'postgres',
            'USER': _url.username or 'postgres',
            'PASSWORD': _url.password or '',
            'HOST': _db_host,
            'PORT': str(_url.port or 5432),
            'OPTIONS': {
                'sslmode': 'require',
            } if _db_host not in ('localhost', '127.0.0.1') else {},
        }
    }
else:
    _db_host = os.environ.get('DJANGO_DB_HOST') or os.environ.get('DB_HOST', '127.0.0.1')
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DJANGO_DB_ENGINE') or os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('DJANGO_DB_NAME') or os.environ.get('DB_NAME', 'edununez'),
            'USER': os.environ.get('DJANGO_DB_USER') or os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD') or os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': _db_host,
            'PORT': os.environ.get('DJANGO_DB_PORT') or os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            } if _db_host not in ('localhost', '127.0.0.1') else {},
        }
    }

if any('pytest' in arg for arg in sys.argv) or 'test' in sys.argv:
    # Usar sqlite3 en memoria para la ejecución ultra-rápida de pytest si PostgreSQL local no está activo
    if os.environ.get('USE_POSTGRES_TESTS', 'False').lower() not in ('true', '1'):
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }

REDIS_URL = os.environ.get('DJANGO_REDIS_URL', 'redis://127.0.0.1:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}
if any('pytest' in arg for arg in sys.argv) or 'test' in sys.argv:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }

JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_HOURS = 1
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@edununez.local')
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('DJANGO_EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'auth.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'EXCEPTION_HANDLER': 'api.utils.exception_handler.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth': '15/min',
        'actividades_completar': '30/min',
        'invitaciones': '10/hour',
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_THROTTLE_CACHE': 'default',
}

# ========== LOGGING ESTRUCTURADO JSON ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.json.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(user_id)s %(duration_ms)s',
        },
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json' if not (any('pytest' in arg for arg in sys.argv) or 'test' in sys.argv) else 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ========== CONFIGURACIÓN CLOUDINARY ==========
import cloudinary

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
)

# Configuración de uploads multimedia
CLOUDINARY_MAX_FILE_SIZE = int(os.environ.get('CLOUDINARY_MAX_FILE_SIZE', 104857600))  # 100MB por defecto
CLOUDINARY_ALLOWED_VIDEO_FORMATS = ['mp4', 'avi', 'mov', 'flv', 'wmv', 'webm', 'mkv']
CLOUDINARY_ALLOWED_AUDIO_FORMATS = ['mp3', 'wav', 'aac', 'flac', 'ogg', 'm4a']
CLOUDINARY_ALLOWED_IMAGE_FORMATS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'usuarios.Usuario' 

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Solo incluir el directorio de build si existe (después de npm run build)
_frontend_static = BASE_DIR.parent / 'frontend' / 'build' / 'static'
STATICFILES_DIRS = [str(_frontend_static)] if _frontend_static.exists() else []

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de sesiones para permitir credenciales en CORS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Cambiar a 'None' si necesitas cross-site
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS

# Configuración CSRF
CSRF_COOKIE_HTTPONLY = False  # Necesario para JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # True en producción con HTTPS

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Permitir CSRF para desarrollo
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# ========== CONFIGURACIÓN N8N / WEBHOOKS ==========
# URL del webhook de n8n. Configurable por entorno para no hardcodear en código fuente.
# En desarrollo: dejar el valor por defecto o definir N8N_WEBHOOK_URL en .env
# En producción: definir N8N_WEBHOOK_URL en las variables de entorno del servidor
N8N_WEBHOOK_URL = os.environ.get(
    'N8N_WEBHOOK_URL',
    'http://localhost:5678/webhook/Alumnos_settings'
)

# Habilitar/deshabilitar el envío de webhooks sin tocar código.
# Útil para entornos de test o cuando n8n no está disponible.
N8N_WEBHOOK_ENABLED = os.environ.get('N8N_WEBHOOK_ENABLED', 'True').lower() in ('true', '1', 'yes')

# Timeout en segundos para la conexión al webhook.
N8N_WEBHOOK_TIMEOUT = int(os.environ.get('N8N_WEBHOOK_TIMEOUT', '10'))

# Reintentos en el envío síncrono (para envío async se fuerza 1).
N8N_WEBHOOK_RETRY_ATTEMPTS = int(os.environ.get('N8N_WEBHOOK_RETRY_ATTEMPTS', '3'))
