# Generated by Django 5.2.3 on 2026-08-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantecurso',
            unique_together={('estudiante', 'curso')},
        ),
    ]
