# Generated by Django 5.2.3 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCienciasNaturales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_tematicas', models.JSONField(default=list, help_text='Unidades temáticas específicas del curso')),
                ('metodologia', models.TextField(blank=True, help_text='Metodología de enseñanza específica')),
                ('evaluacion_criterios', models.JSONField(default=dict, help_text='Criterios de evaluación específicos')),
            ],
            options={
                'verbose_name': 'Curso de Ciencias Naturales',
                'verbose_name_plural': 'Cursos de Ciencias Naturales',
                'db_table': 'api_cursocienciasnaturales',
            },
        ),
        migrations.CreateModel(
            name='MateriaCienciasNaturales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('biologia', 'Biología'), ('fisica', 'Física'), ('quimica', 'Química'), ('ciencias_tierra', 'Ciencias de la Tierra'), ('astronomia', 'Astronomía'), ('ecologia', 'Ecología')], max_length=20)),
                ('nivel_educativo', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato')], max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('temas_principales', models.JSONField(default=list, help_text='Lista de temas principales de la materia')),
                ('objetivos_aprendizaje', models.TextField(blank=True)),
                ('recursos_recomendados', models.JSONField(default=list, help_text='URLs y recursos educativos recomendados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia de Ciencias Naturales',
                'verbose_name_plural': 'Materias de Ciencias Naturales',
                'db_table': 'api_materiacienciasnaturales',
            },
        ),
    ]
