# Generated by Django 5.2.3 on 2026-08-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciencias', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocienciasnaturales',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias_naturales', to='cursos.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='materiacienciasnaturales',
            unique_together={('nombre', 'area', 'nivel_educativo')},
        ),
        migrations.AddField(
            model_name='cursocienciasnaturales',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='ciencias.materiacienciasnaturales'),
        ),
    ]
