# Generated by Django 5.2.3 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url_cloudinary', models.URLField(help_text='URL del archivo alojado en Cloudinary', max_length=500)),
                ('tipo_archivo', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('imagen', 'Imagen')], default='video', help_text='Tipo de archivo multimedia', max_length=20)),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Duración en segundos (para videos y audios)', null=True)),
                ('tamaño_bytes', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(help_text='Referencia a la actividad base', on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Actividad Multimedia',
                'verbose_name_plural': 'Actividades Multimedia',
                'db_table': 'api_actividadmultimedia',
            },
        ),
        migrations.CreateModel(
            name='ActividadTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_limite_minutos', models.IntegerField(blank=True, help_text='Límite de tiempo en minutos. NULL = sin límite', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(help_text='Referencia a la actividad base', on_delete=django.db.models.deletion.CASCADE, related_name='texto', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Actividad Texto',
                'verbose_name_plural': 'Actividades Texto',
                'db_table': 'api_actividadtexto',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='Texto de la pregunta')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación de la pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(help_text='Actividad a la que pertenece esta pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'api_pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto de la opción de respuesta')),
                ('es_correcta', models.BooleanField(default=False, help_text='Marca si esta es la opción correcta')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación de la opción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(help_text='Pregunta a la que pertenece esta opción', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='plantillas.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'db_table': 'api_opcionrespuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['actividad', 'orden'], name='api_pregunt_activid_003b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='opcionrespuesta',
            index=models.Index(fields=['pregunta', 'orden'], name='api_opcionr_pregunt_6dd686_idx'),
        ),
        migrations.AddIndex(
            model_name='opcionrespuesta',
            index=models.Index(fields=['es_correcta'], name='api_opcionr_es_corr_d3c2b6_idx'),
        ),
    ]
