# Generated by Django 5.2.3 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('juego', 'Juego Interactivo'), ('sopa_letras', 'Sopa de letras'), ('crucigrama', 'Crucigrama'), ('palabras', 'Juego de palabras'), ('lectura_comprensiva', 'Lectura Comprensiva'), ('experimento_virtual', 'Experimento Virtual'), ('quiz_ciencias', 'Quiz de Ciencias'), ('simulador', 'Simulador Educativo'), ('laboratorio_virtual', 'Laboratorio Virtual'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('template_type', models.CharField(choices=[('legacy', 'Actividad Antigua'), ('multimedia', 'Plantilla Multimedia'), ('texto', 'Plantilla Texto')], default='legacy', help_text='Tipo de plantilla para esta actividad', max_length=20)),
                ('recurso', models.FileField(blank=True, null=True, upload_to='recursos_actividades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('en_revision', 'En Revisión')], default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'api_actividad',
            },
        ),
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('revisada', 'Revisada'), ('calificada', 'Calificada')], default='asignada', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios_profesor', models.TextField(blank=True, help_text='Comentarios del profesor')),
                ('comentarios_estudiante', models.TextField(blank=True, help_text='Comentarios del estudiante')),
                ('archivo_entrega', models.FileField(blank=True, help_text='Archivo de entrega del estudiante', null=True, upload_to='entregas_actividades/')),
            ],
            options={
                'verbose_name': 'Asignación de Actividad',
                'verbose_name_plural': 'Asignaciones de Actividades',
                'db_table': 'api_asignacionactividad',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('carencias_detectadas', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'api_reporte',
            },
        ),
    ]
