# Generated by Django 5.2.3 on 2026-08-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_por_mi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['curso', 'estado'], name='idx_actividad_curso_estado'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['creado_por', 'created_at'], name='idx_act_creador_fecha'),
        ),
        migrations.AddIndex(
            model_name='asignacionactividad',
            index=models.Index(fields=['estudiante', 'estado'], name='idx_asig_estudiante_estado'),
        ),
        migrations.AddIndex(
            model_name='asignacionactividad',
            index=models.Index(fields=['profesor', 'estado'], name='idx_asig_profesor_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionactividad',
            unique_together={('actividad', 'estudiante')},
        ),
    ]
