# Generated by Django 5.2.3 on 2026-04-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='auth_app_in_created_c9c92f_idx',
            old_name='auth_invi_created_by_57f7c3_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='auth_app_in_created_c3a93e_idx',
            old_name='auth_invi_created_at_b72fbe_idx',
        ),
        migrations.RenameIndex(
            model_name='magiclinktoken',
            new_name='auth_app_ma_token_b0d526_idx',
            old_name='auth_magi_token_3c2ea4_idx',
        ),
        migrations.RenameIndex(
            model_name='magiclinktoken',
            new_name='auth_app_ma_created_51f897_idx',
            old_name='auth_magi_crea_1b8b98_idx',
        ),
    ]
